### ISSUE TITLE
Missing tables for running full suite of programs in the powershell project.

### ISSUE THREAD

**Issue by seniuka** [seniuka/CentralDB#1]

**Comment by seniuka** [comment]
CentralDB_DDL needs to be updated to include the full list of tables, procedures, functions and views.

**Comment by seniuka** [comment]
Geez, fine fine I will add them.

**Comment by rmx198422** [comment]
Hi seniuka ,

I think during the course of last year i was looking for what you created and i only came accross this post in the recently this year. I am trying to test the sp_BlitzWho  i am getting errors. See below and i also put the powershell script below parts that it was complaining about in the error message which i am researching how to resolve and thought id post it here maybe you could help. 

Please let me know if there is any update to the powershell scripts and SQL scripts that i may need to update?

------------------------------------------------------------------------------------
Error Message

Message
Executed as user: xxxxxxxxx. A job step received an error at line 258 in a PowerShell script. The corresponding line is '                            [Parameter()] [ValidateSet(A"ErrorA", A"WarnA", A"InfoA")]  '. Correct the script and reschedule the job. The error information returned by PowerShell is: 'At C:\CentralDB\FirstResponderKit.ps1:258 char:56  +                             [Parameter()] [ValidateSet(A"ErrorA", A"W ...  +                                                        ~ Missing closing ')' in expression.    At C:\CentralDB\FirstResponderKit.ps1:258 char:56  +                             [Parameter()] [ValidateSet(A"ErrorA", A"W ...  +                                                        ~ Parameter declarations are a comma-separated list of variable names with optional initializer expressions.    At C:\CentralDB\FirstResponderKit.ps1:258 char:56  +                             [Parameter()] [ValidateSet(A"ErrorA", A"W ...  +                                                        ~ Missing ')' in function parameter list.    At C:\CentralDB\FirstResponderKit.ps1:259 char:55  +                             [string] $Level = A"InfoA",  +                                                       ~ Missing argument in parameter list.    At C:\CentralDB\FirstResponderKit.ps1:260 char:40  +                             [Parameter()]  +                                        ~ An expression was expected after '('.    At C:\CentralDB\FirstResponderKit.ps1:267 char:82  + ...                [IO.FileInfo] $Path = A"$env:temp\PowerShellLog.txtA",  +                                                                         ~ Missing argument in parameter list.    At C:\CentralDB\FirstResponderKit.ps1:268 char:40  +                             [Parameter()]  +                                        ~ An expression was expected after '('.    At C:\CentralDB\FirstResponderKit.ps1:252 char:1  + {  + ~ Missing closing '}' in statement block or type definition.    At C:\CentralDB\FirstResponderKit.ps1:278 char:21  +                     )  +                     ~ Unexpected token ')' in expression or statement.    At C:\CentralDB\FirstResponderKit.ps1:320 char:5  +     } #Write-Log  +     ~ Unexpected token '}' in expression or statement.    Not all parse errors were reported.  Correct the reported errors and try again.  '.  Process Exit Code -1.  The step failed.

---------------------------------------------------------------------
##############################################################################
##############################################################################

See below i did copy part of the powershell script to show what its complaining about and not really sure what to edit to fix. 

##############################################################################

#Parameter List
param(
	[string]$InstanceName="localhost", #CMS Server with CentralDB
	[string]$DatabaseName="Centraldb", #CMS Server with CentralDB
    [string]$runLocally="false", #This flag is used to reduce the number of remote powershell calls from a single cms
	[string]$type="BZW", #3 Letters from the following sp_Blitz:BLZ, sp_BlitzBackups:BLB, sp_BlitzCache:BZC, p_BlitzFirst:BZF, sp_BlitzIndex:BZI, sp_BlitzQueryStore:BQS, sp_BlitzWho:BZW
	[string]$FirstResponderKitPath="C:\CentralDB", #Where does FirstResponderKit live... the sql files? So we can load the newest version.
	[string]$FirstResponderKitFilter="sp_BlitzWho.sql", #If you rename them... what are they named by default they are sp_Blitz*.sql...
	[string]$logPath="C:\CentralDB\Errorlog\",
	[string]$logFileName="Get-FirstResponderKit_" + $env:computername + ".log"

##############################################################################
############################################################################################################################
Then line 250 to 279

#>
function Write-Log 
{   
            #region Parameters
                    [cmdletbinding()]
                    Param(
                            [Parameter(ValueFromPipeline=$true,Mandatory=$true)] [ValidateNotNullOrEmpty()]
                            [string] $Message,
                            [Parameter()] [ValidateSet(?Error?, ?Warn?, ?Info?)]
                            [string] $Level = ?Info?,
                            [Parameter()]
                            [Switch] $NoConsoleOut,
                            [Parameter()]
                            [String] $ConsoleForeground = 'White',
                            [Parameter()] [ValidateRange(1,30)]
                            [Int16] $Indent = 0,     
                            [Parameter()]
                            [IO.FileInfo] $Path = ?$env:temp\PowerShellLog.txt?,                           
                            [Parameter()]
                            [Switch] $Clobber,                          
                            [Parameter()]
                            [String] $EventLogName,                          
                            [Parameter()]
                            [String] $EventSource,                         
                            [Parameter()]
                            [Int32] $EventID = 1,
                            [Parameter()]
                            [String] $LogEncoding = "ASCII"                         
                    )                   
            #endregion



---
Thanks In Advance
rmx
