### ISSUE TITLE
Get-DeployFile.ps1 Missing from package

### ISSUE THREAD

**Issue by Snubsly** [seniuka/CentralDB#3]
Hi all

So I am taking a shot in the dark here but in trying to run the first responder section I saw the Get-DeployFile.ps1 is missing, do you by any chance still have a copy laying around?

Regards,

**Comment by seniuka** [comment]
Oh my goodness I totally forgot to publish it. Oops I also need to publish
my ola hallegren changes.

Thanks for the reminder

**Comment by Snubsly** [comment]
Awesome looking forward to it! and Thanks

**Comment by seniuka** [comment]
Uploaded missing file. Working on updating a bunch of other scripts but scrubbing any specific work type comments in it. Also need to work with Ola Hallengren to add my GUID column to his scripts.
